import $ from 'jquery';

export var elements = {
  appForm: $(".js-app-form"),
  appInput: $(".js-search-bar-input"),
  appLogo: $(".js-app-logo"),
  appWrapper: $(".js-app"),
  buttonAddTerm: ".js-button-add-term",
  buttonConvert: $(".js-button-convert"),
  buttonOnboard: $(".js-button-onboard"),
  error: $(".js-error"),
  errorWrapper: $(".js-error-wrapper"),
  instructions: $(".js-instructions"),
  landingWrapper: $(".js-landing"),
  nativeDef: ".js-nativeDef",
  searchForm: $(".js-search-form"),
  searchIcon: $(".js-search-bar-icon"),
  searchInput: $(".js-search-page-input"),
  searchPageSearch: $(".js-search-page-input"),
  searchResult: $(".js-search-result-container"),
  searchWrapper: $(".js-search"),
  spinner: $(".js-search-bar-spinner"),
  targetDef: ".js-targetDef",
  term: ".js-term",
  textArea: $(".js-textArea"),
  translation: ".js-translation",
  vocabListItems: $(".js-vocab-list-items"),
};
